In [1]:
import pandas as pd
pd.DataFrame([2])

0
0  2

In [2]:
pd.DataFrame([1,3,4,5])

0
0  1
1  3
2  4
3  5

In [3]:
pd.DataFrame([1,3,4,5] , columns=['A'])

A
0  1
1  3
2  4
3  5

In [4]:
data = [
    [2,1,23 ,7]
]

In [6]:
pd.DataFrame(data)

0  1   2  3
0  2  1  23  7

In [7]:
data = [
    [2,1,23 , 7],
    [2 ,4 ,6 ,12]
]
pd.DataFrame(data)

0  1   2   3
0  2  1  23   7
1  2  4   6  12

In [8]:
pd.DataFrame(data,columns=['A','B','C','D'])

A  B   C   D
0  2  1  23   7
1  2  4   6  12

In [9]:
_tupel=(2,4,3,1)
pd.DataFrame(_tupel)

0
0  2
1  4
2  3
3  1

In [10]:
pd.DataFrame(_tupel , columns=['Values'])

Values
0       2
1       4
2       3
3       1

In [11]:
_2d_tupel = ((2,4,3,1))

In [12]:
pd.DataFrame(_2d_tupel)

0
0  2
1  4
2  3
3  1

In [14]:
_2d_tupel = ((2,4,3,1) ,(21 ,90,2))
pd.DataFrame(_2d_tupel)

0   1  2    3
0   2   4  3  1.0
1  21  90  2  NaN

In [15]:
pd.DataFrame(_2d_tupel , columns=['A','B','C','D'])

A   B  C    D
0   2   4  3  1.0
1  21  90  2  NaN

In [18]:
_dict ={
    'Name':['Lufor'],
    'Id' : [101],
    'DPT':['PSE'],
}

In [19]:
pd.DataFrame(_dict)

Name   Id  DPT
0  Lufor  101  PSE

In [20]:
_dict ={
    'Name':['Lufor' , 'Mean' , 'Natalia','Maria'],
    'Id' : [101 , 302 , 901 , 102],
    'DPT':['PSE' , 'ELL' ,'Math' , 'EEE' ],
}

In [21]:
pd.DataFrame(_dict)

Name   Id   DPT
0    Lufor  101   PSE
1     Mean  302   ELL
2  Natalia  901  Math
3    Maria  102   EEE

In [22]:
_set = {4,5,6, 'Maria'}

In [23]:
pd.DataFrame(_set)

0
0  Maria
1      4
2      5
3      6

In [24]:
pd.DataFrame(_set , columns=['A'])

A
0  Maria
1      4
2      5
3      6

In [25]:
import numpy as np
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
pd.DataFrame(vector)

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [27]:
matrix = np.random.rand(3,4)
matrix

array([[0.661769  , 0.46813376, 0.4771579 , 0.42132569],
       [0.32307813, 0.11513163, 0.22463209, 0.86003889],
       [0.14119321, 0.25345329, 0.80351799, 0.32937968]])

In [28]:
pd.DataFrame(matrix)

0         1         2         3
0  0.661769  0.468134  0.477158  0.421326
1  0.323078  0.115132  0.224632  0.860039
2  0.141193  0.253453  0.803518  0.329380

In [29]:
pd.DataFrame(matrix , columns=['A','B','C','D'])

A         B         C         D
0  0.661769  0.468134  0.477158  0.421326
1  0.323078  0.115132  0.224632  0.860039
2  0.141193  0.253453  0.803518  0.329380

In [30]:
tensor = np.random.rand(3,4,5)

In [31]:
tensor

array([[[0.91688762, 0.2693847 , 0.12537608, 0.37335677, 0.59018612],
        [0.11184045, 0.45702786, 0.68506174, 0.0801775 , 0.62642441],
        [0.81945062, 0.52202903, 0.64386377, 0.06290395, 0.28072405],
        [0.66239056, 0.52245531, 0.42017451, 0.49922534, 0.96949826]],

       [[0.01063708, 0.90555159, 0.75335338, 0.32291913, 0.10806869],
        [0.06246188, 0.65989925, 0.127573  , 0.63581661, 0.56129257],
        [0.20713144, 0.8348906 , 0.62007196, 0.3078908 , 0.21443242],
        [0.2275033 , 0.74992009, 0.34555784, 0.86795233, 0.99044303]],

       [[0.68971598, 0.38506086, 0.84471348, 0.23699342, 0.35049747],
        [0.37753401, 0.39158932, 0.39363286, 0.23603978, 0.14299182],
        [0.23318333, 0.06829192, 0.07995496, 0.02884598, 0.07364609],
        [0.88513636, 0.61146982, 0.36237799, 0.21291917, 0.81533833]]])

In [32]:
pd.DataFrame(tensor)

ValueError: Must pass 2-d input. shape=(3, 4, 5)

In [33]:
import torch
pd.DataFrame(torch.arange(10))

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [34]:
pd.DataFrame(torch.rand(10,10))

0         1         2         3         4         5         6  \
0  0.563367  0.756184  0.225260  0.179148  0.329369  0.472667  0.731364   
1  0.153935  0.919640  0.239383  0.407858  0.714057  0.046846  0.844020   
2  0.231044  0.520548  0.027369  0.457944  0.478391  0.547086  0.181646   
3  0.358560  0.656653  0.695241  0.023744  0.930578  0.739683  0.211151   
4  0.974221  0.144720  0.656223  0.215689  0.188893  0.954332  0.859943   
5  0.594330  0.896734  0.995103  0.239384  0.526195  0.646599  0.801504   
6  0.529744  0.275647  0.033028  0.065509  0.858069  0.750735  0.467164   
7  0.558877  0.727662  0.154222  0.511859  0.645781  0.683901  0.602548   
8  0.017748  0.710352  0.086951  0.977422  0.232540  0.960775  0.252556   
9  0.480214  0.736766  0.916669  0.569875  0.120999  0.674432  0.896451   

          7         8         9  
0  0.586085  0.764070  0.206037  
1  0.849908  0.716665  0.542686  
2  0.826113  0.819250  0.837718  
3  0.316996  0.108481  0.797399  
4  0.041970  0.419986  0.230693  
5  0.683427  0.052783  0.681589  
6  0.754637  0.369162  0.731343  
7  0.114096  0.878434  0.954403  
8  0.654868  0.849148  0.618744  
9  0.628241  0.118071  0.478341

In [35]:
pd.DataFrame(torch.rand(10,3) , columns=['A','B','C'])

A         B         C
0  0.588378  0.099566  0.311701
1  0.422838  0.343636  0.716463
2  0.755019  0.482181  0.828973
3  0.428598  0.266330  0.946923
4  0.967314  0.494008  0.981399
5  0.350639  0.868355  0.835795
6  0.647053  0.685434  0.950011
7  0.333386  0.486740  0.656066
8  0.950422  0.878260  0.292813
9  0.441512  0.611578  0.239633