In [1]:
import pandas as pd

In [3]:
scalar_series=pd.Series(1)

In [4]:
scalar_series

0    1
dtype: int64

In [5]:
scalar_series[0]

np.int64(1)

In [6]:
decimal_series=pd.Series(1.5)
decimal_series

0    1.5
dtype: float64

In [7]:
string_series = pd.Series("Eshrat")
string_series

0    Eshrat
dtype: object

In [8]:
python_list = [2,3,4]
list_series = pd.Series(python_list)

In [9]:
list_series

0    2
1    3
2    4
dtype: int64

In [10]:
list_series[2]

np.int64(4)

In [11]:
string_list=["eshrat" , "anjum" , "erena"]
string_series = pd.Series(string_list)
string_series

0    eshrat
1     anjum
2     erena
dtype: object

In [14]:
 string_series[1]

'anjum'

In [17]:
python_set={2,4,7}
# set_series = pd.Series(python_set)
set_series = pd.Series(list(python_set))
set_series

0    2
1    4
2    7
dtype: int64

In [18]:
pyhon_tuple = (3,7,8)
tuple_series = pd.Series(pyhon_tuple)
tuple_series

0    3
1    7
2    8
dtype: int64

In [19]:
python_dic = {
    'lovel' : 'nothing',
    'care' : 'no',
    'respect':'high'
}

In [20]:
python_dic

{'lovel': 'nothing', 'care': 'no', 'respect': 'high'}

In [21]:
dic_series = pd.Series(python_dic)
dic_series

lovel      nothing
care            no
respect       high
dtype: object

In [22]:
dic_series['lovel']

'nothing'

In [23]:
list1=[1,2,3]
list2=[111 , 222 , 33]

In [24]:
pd.Series(list1 , list2)

111    1
222    2
33     3
dtype: int64

In [26]:
pd.Series('A' , [1])

1    A
dtype: object

In [27]:
pd.Series([True , False , True])

0     True
1    False
2     True
dtype: bool

In [28]:
matrix=[
    [1,2,3],
    [4,5,6],
]

In [29]:
pd.Series(matrix)

0    [1, 2, 3]
1    [4, 5, 6]
dtype: object

In [30]:
import numpy as np
tensor=np.random.rand(2,3,4)
tensor

array([[[0.76723051, 0.41992202, 0.65758622, 0.42558566],
        [0.46850291, 0.85699298, 0.9952104 , 0.20491585],
        [0.6474457 , 0.06742775, 0.0213667 , 0.02905227]],

       [[0.59898076, 0.06715061, 0.29753219, 0.23631858],
        [0.95378858, 0.13824656, 0.28433675, 0.36728825],
        [0.20833024, 0.7385952 , 0.51409533, 0.99414537]]])

In [32]:
# pd.Series(tensor)
vector=np.random.rand(10)
vector

array([0.50657018, 0.63853278, 0.53936885, 0.22722087, 0.87692375,
       0.0102495 , 0.21884798, 0.47806912, 0.0683653 , 0.64167817])

In [33]:
pd.Series(vector)

0    0.506570
1    0.638533
2    0.539369
3    0.227221
4    0.876924
5    0.010250
6    0.218848
7    0.478069
8    0.068365
9    0.641678
dtype: float64

In [34]:
import torch
torch_vector=torch.arange(1,101)
torch_vector

tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100])

In [35]:
pd.Series(torch_vector)

0       1
1       2
2       3
3       4
4       5
     ... 
95     96
96     97
97     98
98     99
99    100
Length: 100, dtype: int64