In [2]:
import numpy as np
ar1 = np.array([12 , 23 , 34 , 55] , dtype=float)
ar2 = np.arange(10 , 99 , 25 , dtype=float)
ar3 = np.arange(10 , 51 , 11 , dtype=float)
ar4 = np.eye(3,6)
ar5 = np.random.normal(50 , 5 , size=(3,6))

In [3]:
print(ar1 +ar2 * 3)

[ 42. 128. 214. 310.]


In [4]:
print(ar4+ar5)

[[37.40658946 44.93989139 53.22739443 41.10034948 40.68311026 51.29981762]
 [47.2713036  48.49112873 60.86175651 45.76544422 56.56414096 57.9872708 ]
 [48.84979647 49.31668972 48.45759687 41.06519277 48.34205654 57.05486844]]


In [5]:
np.add(ar1 , ar2)

array([ 22.,  58.,  94., 140.])

In [7]:
np.add(ar1 , ar2 ,ar3)

array([ 22.,  58.,  94., 140.])

In [8]:
ar5 = np.random.normal(50 , 5 , size=(6,3))
print(ar5.size)

18


In [11]:
# print(ar4 + ar5)

In [12]:
import numpy as np
ar1 = np.array([12 , 23 , 34 , 55] , dtype=float)
ar2 = np.arange(10 , 99 , 25 , dtype=float)
ar3 = np.arange(10 , 51 , 11 , dtype=float)
ar4 = np.eye(3,6)
ar5 = np.random.normal(50 , 5 , size=(3,6))

In [14]:
ar5.sum()

np.float64(867.0634587816769)

In [15]:
ar5.mean()

np.float64(48.1701921545376)

In [16]:
ar5.std()

np.float64(5.410035113265185)

In [17]:
ar5.prod()

np.float64(1.7343970003793795e+30)

In [18]:
ar5.var()


np.float64(29.268479926762243)

In [19]:
ar5.cumsum()

array([ 45.73282919,  94.47510628, 142.00238136, 192.42541553,
       231.4959138 , 279.62422681, 316.9896634 , 364.00766987,
       404.58673593, 455.71517562, 508.97739725, 567.71820125,
       624.15096413, 673.88579545, 718.01310972, 770.96638464,
       818.7099739 , 867.06345878])

In [21]:
import numpy as np 
np_array = np.arange(10)
shape = np_array.shape
print(f"shape : {shape}")

shape : (10,)
