In [22]:
import numpy as np
np_arr = np.eye(3,6)
print(np_arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [23]:
np_arr = np_arr.reshape(6 , 3)
print(np_arr)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [24]:
np_arr = np_arr.reshape(9,2)
print(np_arr)

[[1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]]


In [25]:
np_arr = np_arr.reshape(1,18)
print(np_arr)

[[1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [26]:
np_arr=np_arr.reshape(3,6)
np_arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [27]:
np_arr.resize(6,3)
np_arr

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [28]:
np_arr.ravel()

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0.])

In [29]:
np_arr

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [30]:
np_arr.flatten()

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0.])

In [31]:
np_arr

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [32]:
np_ravel_arr = np_arr.ravel()

In [33]:
np_arr[0,0:] = 9

In [34]:
np_arr

array([[9., 9., 9.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [35]:
np_ravel_arr

array([9., 9., 9., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0.])

In [36]:
np_flatten_arr = np_arr.flatten()
np_arr[-1 , :-1]=88
print(np_arr)

[[ 9.  9.  9.]
 [ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]
 [88. 88.  0.]]


In [37]:
np_flatten_arr

array([9., 9., 9., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0.])