In [1]:
import numpy as np
ar1 = np.array([12 , 23 , 34 , 55], dtype=float)
print(ar1)

[12. 23. 34. 55.]


In [2]:
ar2 = np.eye(3,6,dtype=int)
print(ar2)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]


In [4]:
ar3  = np.arange(10 , 21 , 3)
print(ar3)

[10 13 16 19]


In [5]:
ar4 = np.random.normal(50 , 5 , size=(4 ,5))
print(ar4)

[[50.09329263 48.52325253 52.41290078 44.89017186 57.19293099]
 [47.72338757 56.8111591  57.24019434 47.3832005  44.56053895]
 [56.43479404 54.17820748 48.47441912 50.32046294 49.02376656]
 [50.79351054 44.27840079 51.75767542 50.12738529 52.52827248]]


In [6]:
ar1.ndim

1

In [7]:
ar2.ndim

2

In [8]:
ar2.size

18

In [9]:
ar2.shape

(3, 6)

In [10]:
ar4.shape

(4, 5)

In [11]:
np.sort(ar4)

array([[44.89017186, 48.52325253, 50.09329263, 52.41290078, 57.19293099],
       [44.56053895, 47.3832005 , 47.72338757, 56.8111591 , 57.24019434],
       [48.47441912, 49.02376656, 50.32046294, 54.17820748, 56.43479404],
       [44.27840079, 50.12738529, 50.79351054, 51.75767542, 52.52827248]])

In [14]:
ar4 = np.random.normal(50 , 5 , size=(3 ,6))
np.concat([ar2 ,ar4])

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [54.00955705, 48.70730615, 50.35302881, 40.5376407 , 58.5452284 ,
        55.10305116],
       [54.35131578, 40.63598359, 51.35477583, 40.51959926, 59.09034935,
        45.43897966],
       [42.32313397, 48.67084377, 56.09843058, 45.78960326, 48.31339094,
        53.21550486]])

In [15]:
ar3 = np.arange(10 , 51 , 3)
print(ar3)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [16]:
np.split(ar3 ,[3,5])

[array([10, 13, 16]),
 array([19, 22]),
 array([25, 28, 31, 34, 37, 40, 43, 46, 49])]

In [17]:
np.min(ar3)

np.int64(10)

In [18]:
np.argmin(ar3)

np.int64(0)

In [19]:
np.max(ar3)

np.int64(49)

In [20]:
np.argmax(ar3)

np.int64(13)