In [1]:
import numpy as np
np.array([12, 23 , 34 , 55])

array([12, 23, 34, 55])

In [2]:
np.array([12, 23 , 34 , 55] , dtype=float)

array([12., 23., 34., 55.])

In [3]:
np.empty(10)

array([            nan, 0.00000000e+000, 1.26124233e-311, 2.02369289e-320,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [5]:
np.empty([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(3,6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [8]:
np.eye(3,6 , dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
np.arange(10,21,5) 

array([10, 15, 20])

In [19]:
np.random.rand(10)

0

In [20]:
np.random.rand(2,3)

array([[0.92906572, 0.83547403, 0.77325194],
       [0.43408277, 0.40957086, 0.90803997]])

In [22]:
np.random.randint(0,10, size=(5,5))

array([[9, 6, 9, 4, 0],
       [3, 3, 9, 1, 7],
       [0, 8, 3, 9, 3],
       [6, 9, 0, 5, 3],
       [7, 7, 6, 9, 4]], dtype=int32)

In [23]:
np.random.randint(11,55, size=(5,5))

array([[18, 50, 39, 38, 45],
       [32, 35, 41, 40, 22],
       [24, 31, 31, 24, 19],
       [19, 43, 15, 28, 31],
       [22, 11, 41, 21, 27]], dtype=int32)

In [24]:
np.random.sample(size=(3,5))

array([[0.37815838, 0.49878996, 0.41173821, 0.37401221, 0.64798078],
       [0.08950446, 0.28745438, 0.1995038 , 0.29910402, 0.98032707],
       [0.97016389, 0.83566675, 0.47185199, 0.51074807, 0.57044247]])

In [26]:
np.random.normal(50 , 5 , size=(3,5))

array([[40.28621201, 46.54329275, 58.49839639, 54.76377991, 53.75325558],
       [56.586386  , 48.18703664, 48.66736557, 54.90958758, 52.0990011 ],
       [44.64483334, 50.39548015, 41.93572107, 52.78723908, 45.1435634 ]])