In [1]:
import numpy
np_array = numpy.array([1,2,3,4,5,6,7,8,9,10])
print(np_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
print(np_array[6])

7


In [3]:
print(np_array[:5])

[1 2 3 4 5]


In [4]:
print(np_array[5:])

[ 6  7  8  9 10]


In [6]:
np_2d_arr = numpy.random.normal(100 , 10 , size=(10 , 10))
print(np_2d_arr)

[[106.09710241  93.25756823  99.23252185  96.5921225   94.13617277
   93.93403663 111.29705307  93.70561456  99.77163293  94.48160351]
 [101.95895014  85.19421395  91.17442387 101.18140989 100.81178599
  103.79650836 101.14181405 105.471809   107.68323155 105.47884028]
 [ 97.16054171 120.63970433 111.48420031 100.41565748 100.00762523
  105.03698608 125.83020978 101.6361491  105.33106109  95.02160887]
 [106.1417567   81.1283444  115.35697354  90.8108924  115.55112109
   91.64027533 111.55677886  81.89868337 103.86945709 105.13844774]
 [109.45339983  97.89464872 106.02509036  98.29546735 101.17447765
   91.84073522  90.3434123   94.3082842  109.32167967 106.87431541]
 [120.61919278 123.27155217  93.08959053  96.94751736  90.13798358
   67.27476603 110.74080357 109.6547787  119.61834151  89.13952563]
 [ 93.48245529  93.31875751  79.96196445  95.69945227 110.73724681
   88.68385972 108.9142117  101.47203576 120.28286412 102.89287494]
 [101.07777306 114.74563404 112.54640949 112.80911683  

In [7]:
print(np_2d_arr[0])

[106.09710241  93.25756823  99.23252185  96.5921225   94.13617277
  93.93403663 111.29705307  93.70561456  99.77163293  94.48160351]


In [8]:
print(np_2d_arr[0][0])

106.09710241110503


In [9]:
np_2d_arr[0,0]

np.float64(106.09710241110503)

In [10]:
np_2d_arr[0,0:4]

array([106.09710241,  93.25756823,  99.23252185,  96.5921225 ])

In [11]:
np_2d_arr[1:3 , 1:3]

array([[ 85.19421395,  91.17442387],
       [120.63970433, 111.48420031]])

In [12]:
np_2d_arr=numpy.random.normal(50 , 5 , size=(6 , 5))
print(np_2d_arr)

[[49.922575   49.80432256 49.24515412 57.86535784 48.51448702]
 [44.35093576 48.33846603 48.86907274 55.21401147 53.00941935]
 [48.49810247 48.80713016 58.75682255 58.74471533 48.8711002 ]
 [50.96712888 52.07205083 45.43078553 50.2680623  42.64266377]
 [51.83463886 53.8148549  43.99573047 53.46356634 53.27631616]
 [45.83252855 50.46152532 48.01676989 46.64192137 49.93903351]]


In [13]:
np_2d_arr

array([[49.922575  , 49.80432256, 49.24515412, 57.86535784, 48.51448702],
       [44.35093576, 48.33846603, 48.86907274, 55.21401147, 53.00941935],
       [48.49810247, 48.80713016, 58.75682255, 58.74471533, 48.8711002 ],
       [50.96712888, 52.07205083, 45.43078553, 50.2680623 , 42.64266377],
       [51.83463886, 53.8148549 , 43.99573047, 53.46356634, 53.27631616],
       [45.83252855, 50.46152532, 48.01676989, 46.64192137, 49.93903351]])

In [14]:
np_2d_arr[1:3 , 1:3]

array([[48.33846603, 48.86907274],
       [48.80713016, 58.75682255]])

In [15]:
np_2d_arr[1:-1 , 1:-1]

array([[48.33846603, 48.86907274, 55.21401147],
       [48.80713016, 58.75682255, 58.74471533],
       [52.07205083, 45.43078553, 50.2680623 ],
       [53.8148549 , 43.99573047, 53.46356634]])

In [16]:
np_2d_arr[1:-1 , 1:-1]  = 0
print(np_2d_arr)

[[49.922575   49.80432256 49.24515412 57.86535784 48.51448702]
 [44.35093576  0.          0.          0.         53.00941935]
 [48.49810247  0.          0.          0.         48.8711002 ]
 [50.96712888  0.          0.          0.         42.64266377]
 [51.83463886  0.          0.          0.         53.27631616]
 [45.83252855 50.46152532 48.01676989 46.64192137 49.93903351]]
